# Generated by Django 4.2.11 on 2024-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facilities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
