# Generated by Django 4.2.11 on 2024-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facilities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='icon',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
