# Generated by Django 4.2.11 on 2024-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('service_1', models.CharField(max_length=100)),
                ('service_2', models.CharField(max_length=100)),
                ('service_3', models.CharField(max_length=100)),
                ('service_4', models.CharField(max_length=100)),
            ],
        ),
    ]
