# Generated by Django 4.2.11 on 2024-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
